### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by DanielAlderman** [olbat/dockerfiles#47] opened 2021-01-22 16:29 UTC
Hello,

I was hoping I could get some advice on an issue I'm facing.

I've installed the container using the given command on Docker Hub:

```docker run -d -p 631:631 -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd```

I have also opened port 631 on my server's firewall.

I have a problem however, if I attempt to reach CUPS using my servers DNS and the port I am met with the message "Bad Request".

As far as I understand, I need to change the ServerAlias setting so that CUPS can be accessed externally, but I am a total novice when it comes to Docker and am not sure how I go about this when I do not have access to the files contained with Docker container.

Any advice would be greatly appreciated. The server I have installed this docker container on is running CentOS 8.

Thanks,

Dan

**Comment by olbat** [comment] 2021-01-23 11:08
Hello,

I guess that the issue is related to the fact that you try to access the container using you're machine's external IP (since you're reaching out using your domain name). This needs the port to be published a specific way, see [the documentation](https://docs.docker.com/config/containers/container-networking/#published-ports) on Docker's website. Also, you'll probably need to configure something in the [cupsd configuration file](https://www.suse.com/support/kb/doc/?id=000017214).

Unless it's completely necessary, I would advise you to try to connect on localhost instead of trying to configure the service for remote access. If the container is running on a remote machine, you can always expose local services through [an SSH tunnel](https://www.ssh.com/ssh/tunneling/example) for example.

I hope it'll help. I'm going to close this issue as it's not related to this repository but more to a very specific use-case of one of the containers.

If needed, I'd suggest you to ask for more help on a forum or a user group. Here is a link to the [CentOS forum](https://forums.centos.org/) for example.

Cheers!

**Closed by olbat** 2021-01-23 11:08 UTC
