### ISSUE TITLE
hp 1020 plus 

### ISSUE THREAD

**Issue by hanzch** [olbat/dockerfiles#17] opened 2019-01-14 10:13 UTC
Thank you for sharing! ~

I have two printers, EPSION R1430 is normal
The HP 1020 PLUES 3 drivers tried and could not connect properly.
The specific performance is that after adding a printer, the test page cannot be printed.

Installation command:
`docker run -d -p 631:631 --privileged -v /dev/bus/usb:/dev/bus/usb --name cupsd olbat/cupsd`
PS: Local printer status cannot be found without adding the --privileged parameter.

Look forward to your reply~

**Comment by olbat** [comment] 2019-01-17 07:30
Hi @hanzch, I'm sorry but I think that I won't be able to help you on this issue because 1) it will be hard for me to reproduce and 2) it look more like a _cupsd_ issue than an issue with this specific Docker image.

If you think the issue is with the Docker image, can you please give some more details?

However you'll probably find a better help asking your question on the [cups issue tracker](https://github.com/apple/cups/issues).

Good luck!

**Comment by olbat** [comment] 2019-01-17 17:41
Okay, it might be related to this line from the logs:
`D [17/Jan/2019:10:20:32 +0000] [Job 17] prnt/hpijs/services.cpp 760: dBus Connection Error (Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory)!`.

Can you try to add this to your _docker run_  command: `-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket`?

**Comment by hanzch** [comment] 2019-01-18 03:47
Although the problem has not been solved, thank you for your help and everything goes well~

**Comment by olbat** [comment] 2019-01-18 14:03
Nice :) I close the issue then :)

**Closed by olbat** 2019-01-18 14:03 UTC
